apiVersion: v1
kind: Service
metadata:
  name: angularapp-v2-svc
spec:
  selector: 
    app: webapp-v2
  type: NodePort
  ports:
    - name: http
      port: 3001
      targetPort: 4200
      nodePort: 30002
  

  



