apiVersion: v1
kind: Service
metadata:
  name: angularapp-v1-svc
spec:
  selector: 
    app: webapp-v1
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 4200
      nodePort: 30001



