apiVersion: v1
kind: Pod
metadata:
  name: angularapp-pod-v2
  labels:
    app: webapp-v2
spec:
  containers:
    - name: angularapp-v2-container
      image: karthik1409docker/angularapps:v2
      ports:
        - containerPort: 4200








