apiVersion: v1
kind: Pod
metadata:
  name: nodeapp-usesecret-pod-vol
  labels:
    app: nodeapp-usesecret-pod-vol
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: demosecret
  containers:
    - name: nodeapp-usesecret-pod-vol-container
      image: karthik1409docker/nodeapps:nodeapp-readsecret-vol
      ports:
        - containerPort: 3000
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret
