apiVersion: v1
kind: Pod
metadata:
  name: nodeapp-usesecret-pod
  labels:
    app: nodeapp-usesecret
spec:
  containers:
    - name: nodeapp-usesecret-container
      image: karthik1409docker/nodeapps:nodeapp-consume-k8s-secret
      ports:
        - containerPort: 3000
      envFrom:
        - secretRef:
            name: mysecret1
