apiVersion: v1
kind: Service
metadata:
  name: nodeapp-svc
spec:
  selector: 
    tier: frontend
  type: NodePort
  ports:
    - name: http
      port: 3002
      targetPort: 3000
      nodePort: 30003