apiVersion: v1
kind: Service
metadata:
  name: nodeapp-useconfigmap-svc
spec:
  selector: 
    app: nodeapp-useconfigmap
  type: NodePort
  ports:
    - name: http
      port: 3002
      targetPort: 3000
      nodePort: 30002



