apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: nodeapp-container
          image: karthik1409docker/nodeapps:v1
          ports:
            - containerPort: 3000
