apiVersion: v1
kind: Service
metadata:
  name: nodeapp-usesecret-svc
spec:
  selector: 
    app: nodeapp-usesecret-pod-vol
  type: NodePort
  ports:
    - name: http
      port: 3005
      targetPort: 3000
      nodePort: 30005



